Repository wantedAssignment/jaranda-fe, pull requests merged in 2021-08, with the labels that each got.

#2 Chore(environment): Set up development environment.
  .eslintrc.js
  .prettierrc.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: environment

#8 Feat : userSotrage 구현
  package-lock.json
  src/utils/userStorage.js
Labels: enhancement

#10 Feat: Add pattern & router
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/pages/admin.js
  src/pages/signIn.js
  src/routes/index.js
  src/utils/constants/paths.js
  src/utils/userStorage.js
Labels: environment

#13 Feat: Pagination component basic
  public/img/arrowLeft.png
  public/img/arrowRight.png
  src/containers/pagination/index.js
  src/presentationals/pagination/index.js
Labels: enhancement

#22 Fix: Pagination 오류 수정
  src/containers/pagination/index.js
  src/pages/admin/Admin.js
  src/presentationals/pagination/index.js
Labels: bug

#25 Fix: Pagination 오류 수정
  src/Components/pagination/container.js
  src/Components/pagination/index.js
  src/Components/pagination/presenter.js
  src/pages/admin/Admin.js
Labels: bug

#29 Feat: Add navigation
  src/Components/navigation/container.js
  src/Components/navigation/index.js
  src/Components/navigation/presenter.js
  src/pages/home/container.js
  src/pages/home/index.js
  src/routes/index.js
  src/utils/constants/paths.js
  src/utils/userStorage.js
Labels: enhancement

#32 Feat: Update signUp component.
  package.json
  src/Components/SignUp/container.js
  src/Components/SignUp/presenter.js
  src/hook/useAccount.js
  src/hook/useInput.js
  src/routes/index.js
  src/utils/cardInput.js
  src/utils/constants/paths.js
  src/utils/modal.js
  src/utils/userStorage.js
  yarn.lock
Labels: enhancement

#33 Feature/admin css/#3
  src/Components/Modal.jsx
  src/Components/searchBar/SearchBar.js
  src/Components/searchBar/SearchBar.styles.js
  src/pages/admin/Admin.js
  src/pages/admin/Admin.styles.js
Labels: enhancement

#35 Fix: Change Router PATH constant.
  src/Components/navigation/presenter.js
Labels: bug

#37 Fix: SignIn 관련 삭제
  src/pages/signIn.js
  src/routes/index.js
  src/utils/constants/paths.js
Labels: bug

#45 Feat: Pagination UI 완성
  public/img/arrowLeft.png
  public/img/arrowRight.png
  src/Components/pagination/container.js
  src/Components/pagination/presenter.js
Labels: enhancement

#46 style: Modified styles in signUp component.
  src/Components/SignUp/container.js
  src/Components/SignUp/index.style.js
  src/Components/SignUp/presenter.js
  src/hook/useAccount.js
  src/utils/cardInput.js
  src/utils/modal.js
  yarn.lock
Labels: refactoring

#55 bug: Fix bugs.
  src/pages/signup/index.js
  src/pages/signup/index.style.js
  src/routes/index.js
Labels: bug

#57 Fix: Rename file.
  src/pages/signup/index.js
  src/routes/index.js
Labels: bug
